language: node_js
node-js:
  - lts/*
script:
  - rm -rf dist
  - npm run lint
  - npm run travisBuild

notifications:
  email: false

before_deploy:
  # Set up git user name and tag this commit
  - git config --local user.name "rajdeepiitkgp"
  - git config --local user.email "rajdeep.biswas2010@gmail.com"
  - export TRAVIS_TAG=${TRAVIS_TAG:-$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)}
  - git tag $TRAVIS_TAG

deploy:
  - provider: releases
    api_key: $GITHUB_TOKEN
    skip_cleanup: true
    on:
      branch: main
  - provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
    keep_history: true
    on:
      branch: main
    local_dir: ./dist/aboutme
